name: Run tests

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, macos-latest]
        build_type: [Release, Debug]
        #c_compiler: [gcc, clang, cl]

    steps:
    - uses: actions/checkout@v4

    - name: Set reusable vars
      id: vars
      shell: bash
      run: |
        echo "build_dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Set up MSVC environment on Windows
      # Required for CMake generators other than MSBuild
      if: ${{ runner.os == 'Windows' }}
      uses: TheMrMilchmann/setup-msvc-dev@v4
      with:
          arch: x64

    - name: CMake build
      run: >
        cmake -S ${{ github.workspace }} -G Ninja
        -B ${{ steps.vars.outputs.build_dir }}
        -D CMAKE_BUILD_TYPE=${{ matrix.build_type }}

        cmake --build ${{ steps.vars.outputs.build_dir }}

    - name: Test
      working-directory: ${{ steps.vars.outputs.build_dir }}
      run: ctest
